### PR TITLE
cpp added hit the route /v1/language/cpp

### PR DESCRIPTION
**Pull request by shree1999**
Check it out pls and if anything is missing let me know

### CODE REVIEW

**Comment by MattCSmith** [comment]
@notAnkur Could you confirm the naming convention will work on this one. Thanks 😄

**Comment by MattCSmith** [comment]
Congrats on your first ZTM PR @shree1999

**Comment by notAnkur** [comment]
Yup. Thanks @shree1999 !

**Comment by shree1999** [comment]
I would like to know how can i update my forked repository with the original one.

I am asking this so that I can update my forked repository  without deleting it

**Comment by MattCSmith** [comment]
@shree1999 This article should help with keeping your fork in sync
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Pull request merged**
